name: 'Code sign a file'
description: 'Sign a file with a code signing certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  folder:
    description: 'The folder that contains the libraries to sign.'
    required: true
  recursive:
    description: 'Recursively search for supported files.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
