name: 'Code sign a file'
description: 'Sign a file with a code signing certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  certificate:
    description: 'The base64 encoded certificate.'
    required: true
  password:
    description: 'The certificate password.'
    required: false
  folder:
    description: 'The folder that contains the files to sign.'
    required: false
  recursive:
    description: 'Recursively search for supported files in the specified folder.'
    required: false
  files:
    description: 'The paths to the files to sign.'
    required: false
  description:
    description: 'The description of the signed content.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
